### ISSUE TITLE
Capitulo 1

### ISSUE THREAD

**Issue by gregoryfm** [the-road-to-learn-react/the-road-to-learn-react-portuguese#2]
Página 17, último parágrafo:
**Atual:** É por este motivo `queconst` deveria ser sua escolha padrão quando definindo uma variável.
**Correção:** É por este motivo `que const` deveria ser sua escolha padrão quando definindo uma variável.

Página 24, segundo parágrafo:
**Atual:** Contudo, `você deve dar uma ajudá-lo` a atingir todo o seu potencial e a ter uma melhor performance.`
**Correção:** `Contudo, `você deve ajudá-lo` a atingir todo o seu potencial e a ter uma melhor performance.`

Página 26, segundo parágrafo:
**Atual:** Uma delas é um comportamento diferente `com com` o objeto this.
**Correção:**  Uma delas é um comportamento diferente `com` o objeto this.

**Comment by romerorocha** [comment]
Muito obrigado pela contribuição, @gregoryfm 

Vou tentar aplicar correções de forma bem ágil aqui e mandar para o Leanpub com frequência!

**Comment by gregoryfm** [comment]
Muito bom @romerorocha .

Vou continuar a leitura, caso ache mais alguma coisa abro mais issues.
