### ISSUE TITLE
React Básico

### ISSUE THREAD

**Issue by gregoryfm** [the-road-to-learn-react/the-road-to-learn-react-portuguese#3]
Página 32, primeiro parágrafo: 
**Atual:** Componentes de classe `usam` inicializam seu estado interno utilizando um construtor.
**Sugestão:** Componentes de classe inicializam seu estado interno utilizando um construtor.

Página 36, terceiro parágrafo:
**Atual:** Por que você `utilizar` nomes computados? 
**Sugestão:** Por que você `utilizaria` nomes computados? 

Página 48, terceiro parágrafo:
**Atual:** Uma outra alternativa seria definir a função wrapper em algum outro lugar e passá-la como argumento para `to` tratamento do evento. 
**Sugestão:** Uma outra alternativa seria definir a função wrapper em algum outro lugar e passá-la como argumento para `o` tratamento do evento.

Página 50, segundo parágrafo:
**Atual:** Visando manter o código conciso, você pode transformá-la de volta `uma uma` arrow function, fazendo o mesmo que fizemos com o método de classe onDismiss().
**Sugestão:** Visando manter o código conciso, você pode transformá-la de volta `em uma` arrow function, fazendo o mesmo que fizemos com o método de classe onDismiss().

Página 55, primeiro parágrafo:
**Atual:** Agora, todas as vezes que o `calor` no campo de _input _ muda, você está armazenando o valor
digitado no estado interno do seu componente.
**Sugestão:** Agora, todas as vezes que o `valor` no campo de _input _ muda, você está armazenando o valor digitado no estado interno do seu componente.

Página 55, segundo parágrafo:
**Atual:** Ele preserva o valor das outras propriedades do objeto `estado` quando apenas uma delas é atualizada.
**Sugestão:** Ele preserva o valor das outras propriedades do objeto quando apenas uma delas é atualizada.

Página 57, segundo parágrafo:
**Atual:** Uma última coisa a mencionar: “Apelamos” um pouco, utilizando o `recuso` includes já `de` ES6.
**Sugestão:** Uma última coisa a mencionar: “Apelamos” um pouco, utilizando o `recurso` includes já `do` ES6.

Página 70, segundo parágrafo:
**Atual:** Imagine que possui vários botões em sua `aplicação, quer` mudar um atributo, estilo ou comportamento do botão.
**Sugestão:** Imagine que possui vários botões em sua `aplicação e quer` mudar um atributo, estilo ou comportamento do botão.

Página 79, primeiro parágrafo:
**Atual:** Não se esqueça de usar, como `atributo HTML, className (de React)` no lugar de class.
**Sugestão:** Não se esqueça de usar, como atributo do React, o className no lugar de class.

**Comment by romerorocha** [comment]
Perfeito, aplicarei as correções logo :)

**Comment by romerorocha** [comment]
Apenas este último permanecerá como está, uma vez que continua sendo um atributo em uma tag HTML.
