### ISSUE TITLE
Página 70 - highlight do código

### ISSUE THREAD

**Issue by gregoryfm** [the-road-to-learn-react/the-road-to-learn-react-portuguese#4]
Não sei se foi intencional, mas só o `</button>` ficou vermelho. 

![print](https://user-images.githubusercontent.com/137143/43019532-b59fb2c6-8c33-11e8-876c-0cfe2d42fda3.png)

**Comment by romerorocha** [comment]
Acredito que não seja um bug aqui neste código, apenas o processador de sintaxe JavaScript do Leanpub colore assim o final de alguns elementos. De qualquer forma, obrigado por reportar!
