### ISSUE TITLE
Familiarizando-se com uma API

### ISSUE THREAD

**Issue by gregoryfm** [the-road-to-learn-react/the-road-to-learn-react-portuguese#6]
Página 84, primeiro parágrafo:
**Atual:** Chegou o momento de “melar as mãos” com uma API, uma vez que é `entediaste` lidar sempre com dados estáticos.
**Sugestão:** Chegou o momento de “melar as mãos” com uma API, uma vez que é `entediante` lidar sempre com dados estáticos.

Página 85, primeiro parágrafo:
**Atual:** Será preciso entender sobre métodos de ciclo de vida `de` React antes de começar a obter dados
em seus componentes utilizando uma API. 
**Sugestão:** Será preciso entender sobre métodos de ciclo de vida `do` React antes de começar a obter dados em seus componentes utilizando uma API. 

Página 87, último parágrafo:
**Atual:** Agora, com o uso do componentDidCatch(), você capturar o erro, armazená-lo no estado local e, opcionalmente, exibir uma mensagem para o usuário informando que algo de errado ocorreu.
**Sugestão:** Agora, com o uso do componentDidCatch(), você `pode` capturar o erro, armazená-lo no estado local e, opcionalmente, exibir uma mensagem para o usuário informando que algo de errado ocorreu.

Página 91, primeiro parágrafo:
**Atual:** O componente executa o método render() novamente, mas desta vez com o resultado `poupado` no estado interno.
**Sugestão:** O componente executa o método render() novamente, mas desta vez com o resultado `populado` no estado interno.

Página 105, primeiro parágrafo:
**Atual:** Lembre-se que o método `render()é` chamado antes que os dados sejam, de forma assíncrona, obtidos em componentDidMount().
**Sugestão:** Lembre-se que o método `render() é` chamado antes que os dados sejam, de forma assíncrona, obtidos em componentDidMount().

**Comment by romerorocha** [comment]
A opção de não chamar "O React", mas "React" ao longo do livro, faz com que me refira sempre na forma "de React" ao invés de "do (de + o) React. Achei um pouco estranho acrescentar o artigo antes. Ninguém chama "The React", apenas "React".

Todas as outras sugestões foram muito pertinentes e foram ajustadas 🥇
